function createfigure(X1, Y1, Y2)
%CREATEFIGURE(X1, Y1, Y2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 01-Feb-2016 15:18:45


t = 1:0.001:4;
c = 110./t;

V = 20;
n_max = 4;
d = min(floor(c/V)+1, n_max);

d_min = min(d);
d_max = max(d);
t_idx = zeros(d_max-d_min+1,1);
for nn=1:length(t_idx)
    [~, t_idx(nn)] = find(d == nn+d_min-1,1);
end


%scale it back
d = V*d;

X1 = t;
Y1 = c;
Y2 = d;
% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YTick',[20 40 60 80 100 120],...
    'YColor',[0 0 1],...
    'FontSize',20);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[1 4]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[20 120]);
box(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,Y1,'Parent',axes1,'LineWidth',3,'DisplayName','Original curve');

% Create xlabel
xlabel('$t_e$','Interpreter','latex','FontSize',20);

% Create ylabel
ylabel('$c_e(t_e)$','Interpreter','latex','FontSize',20,'Color',[0 0 1]);

% Create title
title('$V=20.00, N=4$','Interpreter','latex','FontSize',20);

% Create axes
axes2 = axes('Parent',figure1,'YTick',[40 60 80],'YAxisLocation','right',...
    'YColor',[0 0.5 0],...
    'FontSize',20,...
    'ColorOrder',[0 0 1;1 0 0;0 0.75 0.75;0.75 0 0.75;0.75 0.75 0;0.25 0.25 0.25;0 0 1],...
    'Color','none');
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes2,[1 4]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes2,[20 120]);
hold(axes2,'all');

% Create plot
plot(X1,Y2,'Parent',axes2,'LineWidth',3,'LineStyle','-.','Color',[1 0 0],...
    'DisplayName','Quantized curve');

% Create ylabel
ylabel('$\tilde{c}_e(t_e)$','VerticalAlignment','cap','Interpreter','latex',...
    'FontSize',20,...
    'EdgeColor',[0 0 0],...
    'Color',[0 0.5 0]);

% Create legend
legend(axes1,'show');

